apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tekton-demo
spec:
  workspaces:
    - name: manifests-dir
      optional: true
    - name: kubeconfig-dir
      optional: true
  params:
    - name: BUILDER_IMAGE
      description: The image on which builds will run
      default: saripurigopi/dind-kind:latest
    - name: SCRIPT_LOCATION
      description: The location of the kubernetes actions metadata file location
      default: https://github.com/saripurigopi/tekton-demo/tekton/dind-kind.yaml
  resources:
    - name: source
      type: git
  tasks:
    - name: deploy
      taskRef:
        name: kubernetes-actions
      workspaces:
        - name: manifests-dir
          workspace: manifests-dir
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
      params:
        - name: script
          value: |
              kubectl apply -f https://github.com/saripurigopi/tekton-demo/tekton/dind-kind.yaml
    - name: result
      runAfter: [deploy]
      taskRef:
        name: deploy-status
      resources:
        inputs:
          - name: source
            resource: source
